<?php
// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' ); 
?>
<h2>License</h2>
License Version: <?php echo _COMMUNITY_ACL_COMP_NAME;?>
<br />
<hr/>
For more information on the GNU/GPL License please visit: <a href="http://www.gnu.org/licenses/gpl.html" target="_blank">GNU/GPL</a>

<br/>
<iframe src ="http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt" width="100%" height="300">
  <p>Your browser does not support iframes.</p>
</iframe>
<br/><br/>
<h2>Disclaimer</h2>
<hr/>
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS &ldquo;AS IS&rdquo; AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
